BookAPI/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using BookAPI.Models;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using System.Text;
using Newtonsoft.Json.Linq;
using JWT;
using JWT.Algorithms;
using JWT.Serializers;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;

namespace BookAPI.Controllers
{
    public class BooksController : Controller
    {
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(BooksController));
        IConfiguration _config;
        //  private readonly JwtTokenExp tokenclass;
        //code added
        private IJsonSerializer _serializer = new JsonNetSerializer();
        private IDateTimeProvider _provider = new UtcDateTimeProvider();
        private IBase64UrlEncoder _urlEncoder = new JwtBase64UrlEncoder();
        private IJwtAlgorithm _algorithm = new HMACSHA256Algorithm();
        public BooksController(IConfiguration config)
        {

            _config = config;
        }
        [HttpGet]

        public ActionResult Login()
        {
            //HttpContext.Response.Cookies.Delete("Token");
            return View();

        }
        /// <summary>
        /// This method creates the View for Authorized Users
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Login(MemberLogin obj)
        {
            _log4net.Info("User" + obj.Name + " is Logging in");

            string TokenForLogin;
            string data = JsonConvert.SerializeObject(obj);

            try
            {
                Client obj1 = new Client();
                HttpClient client = obj1.Authapi();

                TokenForLogin = GetToken(client, obj);

                if (!string.IsNullOrEmpty(TokenForLogin))
                {

                    HttpContext.Response.Cookies.Append("Token", TokenForLogin);
                    //my added code below  

                    IJwtValidator _validator = new JwtValidator(_serializer, _provider);
                    IJwtDecoder decoder = new JwtDecoder(_serializer, _validator, _urlEncoder, _algorithm);
                    var tokenExp = decoder.DecodeToObject<JwtTokenExp>(TokenForLogin);
                    DateTimeOffset dateTimeOffset = DateTimeOffset.FromUnixTimeSeconds(tokenExp.exp);
                    DateTime timeExp = dateTimeOffset.LocalDateTime;

                    HttpContext.Response.Cookies.Append("Expiry", timeExp.ToString());
                    //my addedcode above
                    HttpContext.Session.SetString("Username", obj.Name);
                    return RedirectToAction("Indes");
                }
                ViewBag.Message = "Invalid Username or Password";
                return View("Login");
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }
        public ActionResult Indes()
        {
            _log4net.Info("User is Entering in to categories page");

            string Token = HttpContext.Request.Cookies["Token"];
            if (string.IsNullOrEmpty(Token))
            {
                return View("Login");
            }
            return View();
        }
        static string GetToken(HttpClient client, MemberLogin user)
        {

            var json = JsonConvert.SerializeObject(user);
            var data = new StringContent(json, Encoding.UTF8, "application/json");

            var response = client.PostAsync("/api/Auth", data).Result;
            if (response.IsSuccessStatusCode)
            {
                string token = response.Content.ReadAsStringAsync().Result;
                return token;
            }

            return null;

        }
        public IActionResult Logout()
        {
            _log4net.Info("User is Logging out");

            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult RegisterUsers()
        {

            return View();
        }
        [HttpPost]
        public async Task<ActionResult> RegisterUsers(Login e)
        {
            _log4net.Info("New User is" + e.LoginId + "Registering");

            Login obj = new Login();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44382/api/Reg/", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("Login");
        }
    


string Baseurl = "https://localhost:44392/";
        public async Task<ActionResult> Index()
        {
            _log4net.Info("User is Shoppiing Books");


            string Token = HttpContext.Request.Cookies["Token"];
            if (string.IsNullOrEmpty(Token))
            {
                return View("Login");
            }
            else
            {
                List<Book> BookDetail = new List<Book>();

                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                    HttpResponseMessage Res = await client.GetAsync("https://localhost:44392/api/Books/");

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (Res.IsSuccessStatusCode)
                    {
                        //Storing the response details recieved from web api   
                        var BookResponse = Res.Content.ReadAsStringAsync().Result;

                        //Deserializing the response recieved from web api and storing into the Employee list  
                        BookDetail = JsonConvert.DeserializeObject<List<Book>>(BookResponse);

                    }
                    //returning the employee list to view  
                    return View(BookDetail);
                }
            }
        }
        [HttpGet]
        public ActionResult AddBook()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> AddBook(Book e)
        {
            Book Bookobj = new Book();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44392/api/Books/", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                   // Bookobj = JsonConvert.DeserializeObject<Book>(apiResponse);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            _log4net.Info("Get Product by " + id + " is invoked");

            Book obj = new Book();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44392/api/Books/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    obj = JsonConvert.DeserializeObject<Book>(apiResponse);
                }
            }
            return View(obj);
        }
        [HttpPost]
        public async Task<ActionResult> Edit(Book obj)
        {
            Book receivedemp = new Book();

            using (var httpClient = new HttpClient())
            {
                #region
                //var content = new MultipartFormDataContent();
                //content.Add(new StringContent(reservation.Empid.ToString()), "Empid");
                //content.Add(new StringContent(reservation.Name), "Name");
                //content.Add(new StringContent(reservation.Gender), "Gender");
                //content.Add(new StringContent(reservation.Newcity), "Newcity");
                //content.Add(new StringContent(reservation.Deptid.ToString()), "Deptid");
                #endregion
                int id = obj.Id;
                StringContent content1 = new StringContent(JsonConvert.SerializeObject(obj), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("https://localhost:44392/api/Books/" + id, content1))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Result = "Success";
                   // receivedemp = JsonConvert.DeserializeObject<Book>(apiResponse);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            _log4net.Info("Get Product by " + id + " is Deleted");

            Book e = new Book();
            e.Id = id;

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44392/api/Books/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    e = JsonConvert.DeserializeObject<Book>(apiResponse);
                }
            }

BookAPI/Controllers/ChatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using BookAPI.Models;
using Microsoft.AspNetCore.Mvc;
using MVC_Assign.Models;
using Newtonsoft.Json;

namespace BookAPI.Controllers
{
    public class ChatsController : Controller
    {
        //string Baseurl = "https://localhost:44391/";
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(ChatsController));

        public async Task<ActionResult> Chaat()
        {
            string Token = HttpContext.Request.Cookies["Token"];
            if (string.IsNullOrEmpty(Token))
            {
                return RedirectToAction("Login", "Books");

            }
            else
            {
                _log4net.Info("user is shopping chaat items");

                List<Chaat> Info = new List<Chaat>();

                using (var client = new HttpClient())
                {
                    //Passing service base url  
                    // client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                    HttpResponseMessage Res = await client.GetAsync("https://localhost:44391/api/Menu/");

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (Res.IsSuccessStatusCode)
                    {
                        //Storing the response details recieved from web api   
                        var Response = Res.Content.ReadAsStringAsync().Result;

                        //Deserializing the response recieved from web api and storing into the Employee list  
                        Info = JsonConvert.DeserializeObject<List<Chaat>>(Response);

                    }
                    //returning the employee list to view  
                    return View(Info);
                }
            }
        }

        public async Task<ActionResult> Drinks()
        {
            List<Drink> Info = new List<Drink>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                // client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("https://localhost:44391/api/Menu/drinks/");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var Response = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    Info = JsonConvert.DeserializeObject<List<Drink>>(Response);
                }
                //returning the employee list to view  
                return View(Info);
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            Chaat ch = new Chaat();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44391/api/Menu/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ch = JsonConvert.DeserializeObject<Chaat>(apiResponse);
                }
            }
            return View(ch);


        }
        [HttpPost]
        public async Task<ActionResult> Edit(Chaat c)
        {
            Chaat receivedemp = new Chaat();

            using (var httpClient = new HttpClient())
            {
                #region
                //var content = new MultipartFormDataContent();
                //content.Add(new StringContent(reservation.Empid.ToString()), "Empid");
                //content.Add(new StringContent(reservation.Name), "Name");
                //content.Add(new StringContent(reservation.Gender), "Gender");
                //content.Add(new StringContent(reservation.Newcity), "Newcity");
                //content.Add(new StringContent(reservation.Deptid.ToString()), "Deptid");
                #endregion
                int id = c.Cid;
                StringContent content1 = new StringContent(JsonConvert.SerializeObject(c), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("https://localhost:44391/api/Menu/" + id, content1))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ViewBag.Result = "Success";
                    receivedemp = JsonConvert.DeserializeObject<Chaat>(apiResponse);
                }
            }
            return RedirectToAction("Chaat");
        }
        public async Task<ActionResult> DetailItems(int id)
        {
            Chaat e = new Chaat();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44391/api/Menu/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    e = JsonConvert.DeserializeObject<Chaat>(apiResponse);
                }
            }
            return View(e);
        }


    }
}

   

BookAPI/Controllers/OnlinePaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using BookAPI.Models;
using BookingClient.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BookAPI.Controllers
{
    public class OnlinePaymentController : Controller
    {
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(OnlinePaymentController));
        [HttpGet]
        public ActionResult Payment()
        {
            string Token = HttpContext.Request.Cookies["Token"];
            if (string.IsNullOrEmpty(Token))
            {
                return RedirectToAction("Login", "Books");

            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public async Task<ActionResult> Payment(PaymentDetail e)
        {
            _log4net.Info(" Product payment of" + e.CardHolderName + "Suceessfull");

            PaymentDetail Emplobj = new PaymentDetail();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:44344/api/Cart/OnlinePay/", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    // Emplobj = JsonConvert.DeserializeObject<Emp>(apiResponse);
                }
            }
            return RedirectToAction("Thanks");
        }
    }
}

BookAPI/Views/Books/AddBook.cshtml
@model BookAPI.Models.Book

@{
    ViewData["Title"] = "AddBook";
}

<h1>AddBook</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddBook">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" class="form-control" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlotDescription" class="control-label"></label>
                <input asp-for="PlotDescription" class="form-control" />
                <span asp-validation-for="PlotDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookAPI/Views/Books/Delete.cshtml
@model BookAPI.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlotDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlotDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookAPI/Views/Books/Indes.cshtml
@model string
@{ ViewData["Title"] = "Index"; }
<style>
    body {
        background-color: #292930;
    }
    h5{
        font-family:Georgia,Arial,Arial, Helvetica;
    }
</style>
<style>
    <style >
    url('https://fonts.googleapis.com/css?family=Muli:400,400i,700,700i');
    .cont {
        font-family: 'Muli', sans-serif;
        background-color: #292930;
    }

    .shell {
        padding: 80px 0;
    }

    .wsk-cp-product {
        background: #fff;
        padding: 15px;
        border-radius: 6px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
        position: relative;
        margin: 20px auto;
        background-color: #105D97;
    }

    .wsk-cp-img {
        position: absolute;
        top: 5px;
        left: 50%;
        transform: translate(-50%);
        -webkit-transform: translate(-50%);
        -ms-transform: translate(-50%);
        -moz-transform: translate(-50%);
        -o-transform: translate(-50%);
        -khtml-transform: translate(-50%);
        width: 100%;
        padding: 15px;
        transition: all 0.2s ease-in-out;
    }

        .wsk-cp-img img {
            width: 100%;
            transition: all 0.2s ease-in-out;
            border-radius: 6px;
            height: 300px;
        }

    .wsk-cp-product:hover .wsk-cp-img {
        top: -40px;
    }

        .wsk-cp-product:hover .wsk-cp-img img {
            box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
        }

    .wsk-cp-text {
        padding-top: 150%;
    }

        .wsk-cp-text .category {
            text-align: center;
            font-size: 12px;
            font-weight: bold;
            padding: 5px;
            margin-bottom: 45px;
            position: relative;
            transition: all 0.2s ease-in-out;
        }

            .wsk-cp-text .category > * {
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%,-50%);
                -webkit-transform: translate(-50%,-50%);
                -moz-transform: translate(-50%,-50%);
                -ms-transform: translate(-50%,-50%);
                -o-transform: translate(-50%,-50%);
                -khtml-transform: translate(-50%,-50%);
            }

            .wsk-cp-text .category > span {
                padding: 12px 30px;
                border: 1px solid #313131;
                background: #212121;
                color: #fff;
                box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
                border-radius: 27px;
                transition: all 0.05s ease-in-out;
            }

    .wsk-cp-product:hover .wsk-cp-text .category > span {
        border-color: #ddd;
        box-shadow: none;
        padding: 11px 28px;
    }

    .wsk-cp-product:hover .wsk-cp-text .category {
        margin-top: 0px;
    }

    .wsk-cp-text .title-product {
        text-align: center;
    }

        .wsk-cp-text .title-product h3 {
            font-size: 20px;
            font-weight: bold;
            margin: 15px auto;
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
            width: 100%;
        }

    .wsk-cp-text .description-prod p {
        margin: 0;
    }
    /* Truncate */
    .wsk-cp-text .description-prod {
        text-align: center;
        width: 100%;
        height: 62px;
        overflow: hidden;
        display: -webkit-box;
        -webkit-line-clamp: 3;
        -webkit-box-orient: vertical;
        margin-bottom: 15px;
    }

    .card-footer {
        padding: 25px 0 5px;
        border-top: 1px solid #ddd;
    }

        .card-footer:after, .card-footer:before {
            content: '';
            display: table;
        }

        .card-footer:after {
            clear: both;
        }

        .card-footer .wcf-left {
            float: left;
        }

        .card-footer .wcf-right {
            float: right;
        }

    .price {
        font-size: 18px;
        font-weight: bold;
    }

    a.buy-btn {
        display: block;
        color: #212121;
        text-align: center;
        font-size: 18px;
        width: 35px;
        height: 35px;
        line-height: 35px;
        border-radius: 50%;
        border: 1px solid #212121;
        transition: all 0.2s ease-in-out;
    }

        a.buy-btn:hover, a.buy-btn:active, a.buy-btn:focus {
            border-color: #FF9800;
            background: #FF9800;
            color: #fff;
            text-decoration: none;
        }

    .wsk-btn {
        display: inline-block;
        color: #212121;
        text-align: center;
        font-size: 18px;
        transition: all 0.2s ease-in-out;
        border-color: #FF9800;
        background: #FF9800;
        padding: 12px 30px;
        border-radius: 27px;
        margin: 0 5px;
    }

        .wsk-btn:hover, .wsk-btn:focus, .wsk-btn:active {
            text-decoration: none;
            color: #fff;
        }

    .red {
        color: #F44336;
        font-size: 22px;
        display: inline-block;
        margin: 0 5px;
    }

    screen and (max-width: 991px) {
        .wsk-cp-product

    {
        margin: 40px auto;
    }

    .wsk-cp-product .wsk-cp-img {
        top: -40px;
    }

        .wsk-cp-product .wsk-cp-img img {
            box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
        }

    .wsk-cp-product .wsk-cp-text .category > span {
        border-color: #ddd;
        box-shadow: none;
        padding: 11px 28px;
    }

    .wsk-cp-product .wsk-cp-text .category {
        margin-top: 0px;
    }

    a.buy-btn {
        border-color: #FF9800;
        background: #FF9800;
        color: #fff;
    }

    }
</style>
<div class="container text-center">
    <h1 style="color:ghostwhite" class="display-4">Welcome To United Online Mega Mall !!</h1>
    <h5 style="color:ghostwhite">Choose any Categories to shop</h5>

</div>


<div class="shell">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="wsk-cp-product">
                    <div class="wsk-cp-img">
                        <img src="/assets/book_photo.jpg" alt="Product" class="img-responsive" height="300" />
                    </div>
                    <div class="wsk-cp-text">
                        <div class="category">
                            <a asp-action="Index" asp-controller="Books" class="col btn btn-outline-light m-2">ShopBooks</a>
                        </div>
                        <div class="title-product">
                        </div>


                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wsk-cp-product">
                    <div class="wsk-cp-img"><img src="/assets/chat.jpg" alt="Product" class="img-responsive" height="300" /></div>
                    <div class="wsk-cp-text">
                        <div class="category">
                            <a asp-action="chaat" asp-controller="Chats" class="col btn btn-outline-light m-2">Order Chat Items</a>
                        </div>
                        <div class="title-product">
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wsk-cp-product">
                    <div class="wsk-cp-img"><img src="/assets/Register.jpg" alt="Product" class="img-responsive" height="300" /></div>
                    <div class="wsk-cp-text">
                        <div class="category">

                            <a asp-action="Index" asp-controller="Booking" class="col btn btn-outline-light m-2">Book Movies</a>
                        </div>


                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wsk-cp-product">
                    <div class="wsk-cp-img"><img src="/assets/gadjets.jpg" alt="Product" class="img-responsive" height="300" /></div>
                    <div class="wsk-cp-text">
                        <div class="category">
                            <a asp-action="Index" asp-controller="Product" class="col btn btn-outline-light m-2">Shop Products and Gadgets</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

BookAPI/Views/Books/PaymentsMode.cshtml
<h1>PaymentsMode</h1>
<style>
    .br {
        background-size: auto;
        background-repeat: no-repeat;
        min-width: 100%;
        margin-top: -40px;
        position: absolute;
        left: -100%;
        right: -100%;
        margin: auto;
        top: 10%;
    }

    #on {
        position: absolute;
        top: 40%;
        font-size: 30px;
        left: 50%
    }

    #cod {
        position: absolute;
        top: 40%;
        font-size: 30px;
        left: 80%;
    }

    body {
        background-color: #2b6777;
    }

    h1 {
        color: #f2f2f2;
    }
</style>
<img src="~/assets/jjj.jpg" height="450" width="500" />
<div class="container">
    <a input type="submit" id="on" asp-controller="OnlinePayment" asp-action="Payment" class="btn btn-success">Payment By Online</a>
    <a input type="submit" id="cod" asp-controller="Books" asp-action="Thanks" class="btn btn-success">Cash on Delivery</a>

</div>